[project]
name = "vibe-app"
version = "0.0.1"
description = "Vibe demo package"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["fastapi"]
[build-system]
requires = ["setuptools>=68","wheel","build"]
build-backend = "setuptools.build_meta"
